#!/bin/bash

#  docker run -p 80:8080 -p 59000-59100:59000-59100/udp --cap-add SYS_ADMIN --shm-size=1gb belleepoke/visionhub:chromium 
#  docker run -p 80:8080 -p 59000-59100:59000-59100/udp --shm-size=1gb belleepoke/visionhub:firefox
#  docker run --network host --shm-size=1gb -it belleepoke/visionhub:base /bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/.."

build_gst() {
  if [ ! -L /c/tmp/gst || ! -d /c/tmp/gst ]; then
     rm -rf /c/tmp/gst;
     mkdir -p /c/tmp/gst;
     mkdir -p /c/tmp/workspace/.build/gst
     ln -s /c/tmp/workspace/.build/gst /c/tmp/gst
     chown -R neko /c/tmp/workspace/.build
  fi
  
  #
  # build & install gstreamer 

}

build_base() {
  set -eux; \
    cd $DIR/server; go get -v -t -d . ; ./build; \
    cd $DIR/client; npm install; npm run build; \
    cd $DIR;  docker build -f .docker/files/base/Dockerfile -t belleepoke/visionhub:base . ;
}

build_latest() {
  set -eux; \
   cd $DIR;  docker build -f .docker/files/$1/Dockerfile -t belleepoke/visionhub:latest . ; 
}

build_image() {
  set -eux; \
    cd $DIR;  docker build -f .docker/files/$1/Dockerfile -t belleepoke/visionhub:$1 . ; 
}

build() {
  if [ ! -d /gst/local ]; then
    build_gst
  fi

  if [ $1 != "" ]; then
    build_image $1
  else
    set -eux; \
      build_image "deps"; \
      build_image "base"; \
      build_base; \
      build_image "openbox"; \
      build_image "xfce4"; \
      build_image "jwm"; \
      build_image "firefox"; \
      build_image "chromium"; \
      build_image "tor-browser";
  fi

   docker images belleepoke/visionhub 
}

push() {
  if [ $1 != "" ]; then
     docker push belleepoke/visionhub:$1
  else
     docker push belleepoke/visionhub:deps 
     docker push belleepoke/visionhub:base 
     docker push belleepoke/visionhub:openbox 
     docker push belleepoke/visionhub:xfce4 
     docker push belleepoke/visionhub:jwm 
     docker push belleepoke/visionhub:firefox 
     docker push belleepoke/visionhub:chromium 
     docker push belleepoke/visionhub:tor-browser 
  fi
}

case $1 in
  images) build;;
  image) build $2 ;;
  push) push $2 ;;
  latest) build_latest ;;
  base) build_image "base" ;;
  deps) build_image "deps" ;;
  dev) build_image "dev" ;;
  gst) build_gst ;;
  *) build_docker ;;
esac
